# Dockerfile for creating a deployable container for bet-scraper

# Install base stuff
FROM poltak/bet-scraper:cron
ENV REFRESHED_AT 2016-07-01
MAINTAINER Jonathan Poltak Samosir <jonathan.samosir@gmail.com>

# Set work directory for all build commands
WORKDIR /bet_scraper

# Forever watch the log file, making it the container's log
CMD ["cron", "&&", "tail", "-f", "/var/log/cron.log"]

