version: '2'

services:

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile-70
        restart: always
        volumes_from:
            - application
        expose:
            - "9000"
        links:
            - workspace
        network_mode: bridge

### Laravel Application Code Container ######################

    application:
        build: ./application
        restart: always
        volumes:
            - ../:/var/www/laravel
        network_mode: bridge

### Nginx Server Container ##################################

    nginx:
        build: ./nginx
        restart: always
        volumes_from:
            - application
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "8080:80"
            - "443:443"
        links:
            - php-fpm
        network_mode: bridge

### MongoDB Container #########################################

    mongodb:
        build: ./mongodb
        container_name: mongodb
        restart: always
        volumes:
            - /var/lib/mongodb/:/data/db
            - /opt/mongodb/mongodb.conf:/mongodb.conf
            - /data/configdb
        ports:
            - "27017:27017"
        network_mode: bridge

### Workspace Utilities Container ###########################

    workspace:
        build: ./workspace
        restart: always
        volumes_from:
            - application
        tty: true
        network_mode: bridge

### tor Container #######################################

  tor-instance:
    container_name: tor-instance
    restart: always
    image: rdsubhas/tor-privoxy-alpine
    network_mode: bridge
    ports:
      - "127.0.1.1:9050:9050"
      - "127.0.1.1:8118:8118"

### bet-scraper Container #######################################

  bet-scraper:
    container_name: bet-scraper
    restart: always
    build:
      context: ./bet-scraper
      dockerfile: Dockerfile
    volumes:
      - ../:/bet_scraper
    network_mode: bridge
    links:
      - tor-instance
      - mongodb
    environment:
      - http_proxy=tor-instance:8118
